addons:
  apt:
    packages:
    - ant
    
    #env:
    #  # one build with and without numpy support (opt numpy out)
    #  #- NUMPY="--global-option=--disable-numpy"
    #  - NUMPY=""
    #
  matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial
      language: python
      PYTHON="python3"

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      PYTHON="python3"

      #- python: 'pypy'
      #  env: NUMPY="--global-option=--disable-numpy"
      #- python: 'pypy3'
      #  env: NUMPY="--global-option=--disable-numpy"
      #- python: 'pypy'
      #  env: NUMPY=""
      #- python: 'pypy3'
      #  env: NUMPY=""
      #- python: 'nightly'
      #  env: NUMPY=""
      #- python: 'nightly'
      #  env: NUMPY="--global-option=--disable-numpy"
  
install:
  - $PYTHON setup.py --enable-build-jar sdist
  - $PYTHON -m pip install --user dist/* $NUMPY
  - $PYTHON -m pip install --user -r test-requirements.txt
  - ant -f test/build.xml

script:
  - $PYTHON -c "import jpype"
  - $PYTHON -m pytest -v test/jpypetest
