os:
  - linux

language: python

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy3'
  - "nightly"

env:
  - PYTHON=python INST=""

addons:
  apt:
    packages:
    - ant

matrix:
  include:
    - name: "Python 2.7 on Xenial Linux (w/o NUMPY)"
      python: 2.7
      dist: xenial
      language: python
      env:
        - PYTHON=python
        - INST=""
        - NUMPY="--global-option=--disable-numpy"

    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      dist: xenial
      language: python
      env:
        - PYTHON=python
        - INST=""

    - name: "Python 3.7 on Xenial Linux (w/o NUMPY)"
      python: 3.7
      dist: xenial
      language: python
      env:
        - PYTHON=python3
        - INST=""
        - NUMPY="--global-option=--disable-numpy"

    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
      language: python
      env:
        - PYTHON=python3
        - INST=""

    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: java
      env:
        - PYTHON=python
        - INST=--user
      addons:
        homebrew:
          packages:
            - ant

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: java
      env:
        - PYTHON=python3
        - INST=--user
      addons:
        homebrew:
          packages:
            - ant

install:
  - $PYTHON setup.py sdist
  - $PYTHON -m pip install $INST dist/* $NUMPY
  - $PYTHON -m pip install $INST -r test-requirements.txt
  - ant -f test/build.xml

script:
  - $PYTHON -c "import jpype"
  - $PYTHON -m pytest -v test/jpypetest
