os:
  - linux

language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - 'nightly'
  - 'pypy3'

env:
  global:
    - PYTHON=python
    - PIP=pip
    - INST=""

addons:
  apt:
    packages:
    - ant

matrix:
  allow_failures:
    - python: nightly
    - python: pypy3

  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
      language: python
      env:
        - PYTHON=python3
        - PIP=pip3

    - name: "Python 3.7 on Xenial Linux coverage"
      python: 3.7
      dist: xenial
      language: python
      env:
        - PYTHON=python3
        - PIP=pip3
      install:
        - $PYTHON setup.py --enable-coverage --enable-build-jar build_ext --inplace
        - $PYTHON setup.py install
        - $PIP install -e .
        - $PIP install gcovr pytest-cov
        - mvn -f project/coverage package
        - ant -f test/build.xml
      script:
        - $PYTHON -m pytest -v test/jpypetest --cov=jpype --cov-report=xml:coverage_py.xml --jar="native/org.jpype.jar" --jacoco
        - gcovr -r . --xml -o coverage.xml -d
        - java -jar project/coverage/org.jacoco.cli-0.8.5-nodeps.jar report jacoco.exec --classfiles build/classes/ --xml coverage_java.xml
        - bash <(curl -s https://codecov.io/bash) -f coverage.xml -f coverage_py.xml -f coverage_java.xml
    
    - name: "Python on macOS xcode 10.3"
      os: osx
      osx_image: xcode10.3
      language: java
      env:
        - PYTHON=python3
        - INST=--user
        - PIP=pip3
      addons:
        homebrew:
          packages:
            - ant

    - name: "Python on macOS xcode 11.3"
      os: osx
      osx_image: xcode11.3
      language: java
      env:
        - PYTHON=python3
        - INST=--user
        - PIP=pip3
      addons:
        homebrew:
          packages:
            - ant


install:
  - echo $PYTHON $INST
  - $PYTHON setup.py sdist
  - $PIP install $INST dist/* $NUMPY
  - $PIP install $INST -r test-requirements.txt
  - ant -f test/build.xml

script:
  - $PYTHON -c "import jpype"
  - $PYTHON -m pytest -v test/jpypetest

