# JPype CI pipeline
trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - .azure/build.yml
    - doc/*
    - setup.py
    - setupext/*
    - jpype/*
    - native/*
    - test/*

variables:
# indicate whether the testsuite should skip long running tests or not.
- name: jpypetest.fast
  value: 'false'

jobs:
- job: Deps
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/ivy.yml

- job: Documentation
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/documentation.yml

- job: Coverage
  pool:
    vmImage: "ubuntu-latest"
  dependsOn: Deps
  steps:
  - template: scripts/deps.yml
  - template: scripts/coverage.yml

- job: Tracing
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/tracing.yml

- job: Test
  dependsOn: Deps
  strategy:
    matrix:
      # Linux
      linux-3.8:  # todo: 3.8 will be EOL on October 31, 2024
        imageName: "ubuntu-latest"
        python.version: '3.8'
        jdk.version: '8'
      linux-3.9:
        imageName: "ubuntu-latest"
        python.version: '3.9'
        jdk.version: '11'
      linux-3.10:
        imageName: "ubuntu-latest"
        python.version: '3.10'
        jdk.version: '17'
      linux-3.11:
        imageName: "ubuntu-latest"
        python.version: '3.11'
        jdk.version: '17'
      linux-3.12:
        imageName: "ubuntu-latest"
        python.version: '3.12'
      # Windows
      windows-3.8:
        imageName: "windows-2019"
        python.version: '3.8' # todo: 3.8 will be EOL on October 31, 2024
        jdk.version: '8'
      windows-3.9:
        imageName: "windows-2019"
        python.version: '3.9'
        jdk.version: '11'
      windows-3.10:
        imageName: "windows-2019"
        python.version: '3.10'
      windows-3.11:
        imageName: "windows-2019"
        python.version: '3.11'
        jdk.version: '17'
      windows-3.12:
        imageName: "windows-2019"
        python.version: '3.12'
        jdk.version: '21'
      # OSX
      mac-3.8:
        imageName: "macos-12"
        python.version: '3.8' # todo: 3.8 will be EOL on October 31, 2024
        jpypetest.fast: 'true'
        jdk.version: '8'
      mac-3.12:
        imageName: "macos-12"
        python.version: '3.12'
        jpypetest.fast: 'true'
        jdk.version: '17'

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/deps.yml
  - template: scripts/test.yml

- job: Debug
  condition: eq(1,0)
  dependsOn: Deps
  strategy:
    matrix:
      linux-3.8:
        imageName: "ubuntu-16.04"
        jdk.version: "11"
        python.version: '3.8'
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/deps.yml
  - template: scripts/debug.yml
