# JPype CI pipeline
pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - .azure/build.yml
    - doc/*
    - setup.py
    - setupext/*
    - jpype/*
    - native/*
    - test/*

jobs:
- job: Documentation
  condition: eq(1,0)
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: scripts/documentation.yml

- job: Coverage
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: scripts/coverage.yml

- job: Tracing
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: scripts/tracing.yml

- job: Test
  condition: eq(1,0)
  strategy:
    matrix:
      linux-3.5:
        imageName: "ubuntu-16.04"
        python.version: '3.5'
      linux-3.6:
        imageName: "ubuntu-16.04"
        python.version: '3.6'
      linux-3.7:
        imageName: "ubuntu-16.04"
        python.version: '3.7'
      linux-3.8:
        imageName: "ubuntu-16.04"
        python.version: '3.8'
      windows-3.5:
        imageName: "vs2017-win2016"
        python.version: '3.5'
      windows-3.6:
        imageName: "vs2017-win2016"
        python.version: '3.6'
      windows-3.7:
        imageName: "vs2017-win2016"
        python.version: '3.7'
      windows-3.8:
        imageName: "vs2017-win2016"
        python.version: '3.8'
      mac-3.8:
        imageName: "macos-10.14"
        python.version: '3.8'
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/test.yml

- job: Debug
  condition: eq(1,0)
  strategy:
    matrix:
      linux-3.8:
        imageName: "ubuntu-16.04"
        jdk_version: "1.11"
        python.version: '3.8'
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/debug.yml

- job: IvyTest
  condition: eq(1,0)
  strategy:
    matrix:
      linux-3.5:
        imageName: "ubuntu-16.04"
      windows-3.5:
        imageName: "vs2017-win2016"
      mac-3.8:
        imageName: "macos-10.14"

  steps:
  - script: |
      wget "https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar" -P lib
      java -jar lib/ivy-2.4.0.jar -ivy ivy.xml -retrieve 'lib/[artifact].[ext]'
    displayName: 'Test ivy'


